on:
  push:
    branches:
      - 'main'
    paths:
      - 'DESCRIPTION'
  workflow_dispatch:

jobs:
  drat-upload:
    runs-on: ubuntu-20.04
    name: Drat Upload
    steps:
      - uses: mikemahoney218/upload-to-drat-repo@v0.2.1
        with:
          drat_repo: 'mikemahoney218/drat'
          token: "${{ secrets.DRAT_TOKEN }}"
          commit_message: "Automated update (add terrainr)"
          commit_email: "mike.mahoney.218@gmail.com"
